# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/zybo_z7_20_base_20202/zybo_z7_20_base_20202.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_z7_20_base_20202 || ORIG_REF_NAME==zybo_z7_20_base_20202} -quiet] -quiet

# IP: bd/zybo_z7_20_base_20202/ip/zybo_z7_20_base_20202_processing_system7_0_0_1/zybo_z7_20_base_20202_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_z7_20_base_20202_processing_system7_0_0 || ORIG_REF_NAME==zybo_z7_20_base_20202_processing_system7_0_0} -quiet] -quiet

# IP: bd/zybo_z7_20_base_20202/ip/zybo_z7_20_base_20202_clk_wiz_0_0_1/zybo_z7_20_base_20202_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_z7_20_base_20202_clk_wiz_0_0 || ORIG_REF_NAME==zybo_z7_20_base_20202_clk_wiz_0_0} -quiet] -quiet

# IP: bd/zybo_z7_20_base_20202/ip/zybo_z7_20_base_20202_proc_sys_reset_0_0_1/zybo_z7_20_base_20202_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_z7_20_base_20202_proc_sys_reset_0_0 || ORIG_REF_NAME==zybo_z7_20_base_20202_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/zybo_z7_20_base_20202/ip/zybo_z7_20_base_20202_proc_sys_reset_0_1_1/zybo_z7_20_base_20202_proc_sys_reset_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_z7_20_base_20202_proc_sys_reset_0_1 || ORIG_REF_NAME==zybo_z7_20_base_20202_proc_sys_reset_0_1} -quiet] -quiet

# IP: bd/zybo_z7_20_base_20202/ip/zybo_z7_20_base_20202_proc_sys_reset_0_2_1/zybo_z7_20_base_20202_proc_sys_reset_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_z7_20_base_20202_proc_sys_reset_0_2 || ORIG_REF_NAME==zybo_z7_20_base_20202_proc_sys_reset_0_2} -quiet] -quiet

# IP: bd/zybo_z7_20_base_20202/ip/zybo_z7_20_base_20202_xlconcat_0_0_1/zybo_z7_20_base_20202_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_z7_20_base_20202_xlconcat_0_0 || ORIG_REF_NAME==zybo_z7_20_base_20202_xlconcat_0_0} -quiet] -quiet

# XDC: /home/ayuba/workspace/THESIS/hardware/zybo_z7_20_base_20202-vivado/zybo_z7_20_base_20202-vivado.gen/sources_1/bd/zybo_z7_20_base_20202/zybo_z7_20_base_20202_ooc.xdc
